// Code generated by go generate; DO NOT EDIT.
// Source: ../../ez-contract/schemas/responses/responses.yaml

package contract

import (
	"fmt"
	"sort"
	"strings"
)

const (
	ResponsesEventOutputTextDelta     = "response.output_text.delta"
	ResponsesEventOutputToolCallDelta = "response.output_tool_call.delta"
	ResponsesEventCompleted           = "response.completed"
	ResponsesEventError               = "response.error"
)

type ResponsesFieldDecision string

const (
	ResponsesFieldDecisionPassThrough ResponsesFieldDecision = "pass_through"
	ResponsesFieldDecisionReject      ResponsesFieldDecision = "reject"
	ResponsesFieldDecisionDegrade     ResponsesFieldDecision = "degrade"
)

var responsesPassThroughRequestFields = map[string]struct{}{
	"frequency_penalty":     {},
	"input":                 {},
	"instructions":          {},
	"max_completion_tokens": {},
	"max_output_tokens":     {},
	"metadata":              {},
	"model":                 {},
	"parallel_tool_calls":   {},
	"presence_penalty":      {},
	"seed":                  {},
	"stream":                {},
	"temperature":           {},
	"tool_choice":           {},
	"tools":                 {},
	"top_p":                 {},
	"user":                  {},
}

var responsesRejectedRequestFields = map[string]struct{}{
	"conversation":         {},
	"include":              {},
	"previous_response_id": {},
	"reasoning":            {},
	"text":                 {},
	"truncation":           {},
}

func ResponsesRequestFieldDecision(field string) ResponsesFieldDecision {
	normalized := strings.ToLower(strings.TrimSpace(field))
	if normalized == "" {
		return ResponsesFieldDecisionDegrade
	}
	if _, ok := responsesPassThroughRequestFields[normalized]; ok {
		return ResponsesFieldDecisionPassThrough
	}
	if _, ok := responsesRejectedRequestFields[normalized]; ok {
		return ResponsesFieldDecisionReject
	}
	return ResponsesFieldDecisionDegrade
}

func ValidateResponsesRequestFields(payload map[string]any) error {
	for key := range payload {
		if ResponsesRequestFieldDecision(key) == ResponsesFieldDecisionReject {
			return fmt.Errorf("unsupported field %q", strings.ToLower(strings.TrimSpace(key)))
		}
	}
	return nil
}

func ResponsesPassThroughRequestFields() []string {
	return sortedResponseFields(responsesPassThroughRequestFields)
}

func ResponsesRejectedRequestFields() []string {
	return sortedResponseFields(responsesRejectedRequestFields)
}

func sortedResponseFields(src map[string]struct{}) []string {
	if len(src) == 0 {
		return nil
	}
	out := make([]string, 0, len(src))
	for field := range src {
		out = append(out, field)
	}
	sort.Strings(out)
	return out
}
